export const SEED_DATA = {
  "parties": [
    {
      "id": "1",
      "ledger_no": "MLP - 001",
      "party_name": "SAANAVI ENTERPRISE",
      "address": "SAIDHAM RESIDANCY AA/22 ANKLESHWAR, 393001, NEAR MULAD CHOWKDI, GUJARAT-393001",
      "gst_no": "24BESPD3841P1Z1",
      "mobile": "",
      "email": ""
    },
    {
      "id": "2",
      "ledger_no": "MLP - 002",
      "party_name": "MANOJ & CO.",
      "address": "D.C.C. COLONY , D.C.C. MARKET SIKKA, JAMNAGAR, GUJARAT, 361140",
      "gst_no": "24AACH1790E1Z5",
      "mobile": "",
      "email": ""
    },
    {
      "id": "3",
      "ledger_no": "MLP - 003",
      "party_name": "SHREE DWARKADHISH ENTERPRISE",
      "address": "SECOND FLOOR, NEAR J M BAXI, THE PRIME, SHOP NO. SF/201, BEDI, JAMNAGAR 361009\n",
      "gst_no": "24AACPH1792G1ZZ",
      "mobile": "",
      "email": ""
    },
    {
      "id": "4",
      "ledger_no": "MLP - 004",
      "party_name": "DIGVIJAY MINERALS",
      "address": "SURVEY NO 93/P1 AND 93/P2 LAKHOND KALI TALAVDI ROAD, KALI TALAVDI, BHUJ,KUTCHCHH,GUJARAT, 370001",
      "gst_no": "24AASFD1386N1ZV",
      "mobile": "",
      "email": ""
    },
    {
      "id": "5",
      "ledger_no": "MLP - 005",
      "party_name": "SHREE SATGURU TRANSPORT",
      "address": "plot no 23, sadguru smart village, moti bhujpur, taluka mundra, dist : kachchh, pincode - 370405\n",
      "gst_no": "24EQAPS4036L1ZN",
      "mobile": "",
      "email": ""
    },
    {
      "id": "6",
      "ledger_no": "MLP - 006",
      "party_name": "YADUNANDAN LOGISTICS",
      "address": "SHOP NO-3, HARI OM AVENUE, NR SHAINIK BHAVAN,KAHMBHALIYA ROA , JAMNAGAR, GUJARAT - 361005",
      "gst_no": "24AXPPT9220P1ZL",
      "mobile": "",
      "email": ""
    }
  ],
  "party_payments": [
    {
      "id": "4",
      "party_name": "YADUNANDAN LOGISTICS",
      "payment_date": "2026-08-01",
      "amount": 66263.0,
      "payment_mode": "BANK",
      "reference": "GOOGLE PAY",
      "notes": "UPI"
    },
    {
      "id": "3",
      "party_name": "DIGVIJAY MINERALS",
      "payment_date": "2026-07-23",
      "amount": 62464.0,
      "payment_mode": "BANK",
      "reference": "NEFT",
      "notes": ""
    },
    {
      "id": "2",
      "party_name": "MANOJ & CO.",
      "payment_date": "2026-07-18",
      "amount": 29088.0,
      "payment_mode": "BANK",
      "reference": "NEFT",
      "notes": ""
    },
    {
      "id": "1",
      "party_name": "SHREE DWARKADHISH ENTERPRISE",
      "payment_date": "2026-07-18",
      "amount": 150000.0,
      "payment_mode": "BANK",
      "reference": "NEFT",
      "notes": ""
    }
  ],
  "trucks": [
    {
      "id": "13",
      "truck_no": "GJ 03 BT 5925",
      "owner_name": "BHIMSHIBHAI",
      "owner_mobile": "",
      "bank_details": "IDBI"
    },
    {
      "id": "11",
      "truck_no": "GJ 03 BW 4387",
      "owner_name": "MUKESHBHAI",
      "owner_mobile": "",
      "bank_details": "hdfc"
    },
    {
      "id": "1",
      "truck_no": "GJ 03 CU 3351",
      "owner_name": "BHURABHAI",
      "owner_mobile": "",
      "bank_details": "ICICI BANK"
    },
    {
      "id": "21",
      "truck_no": "GJ 03 CU 3818",
      "owner_name": "KANZARIYA",
      "owner_mobile": "",
      "bank_details": ""
    },
    {
      "id": "8",
      "truck_no": "GJ 03 CU 5608",
      "owner_name": "AAL LALABHAI",
      "owner_mobile": "",
      "bank_details": "kotak"
    },
    {
      "id": "19",
      "truck_no": "GJ 03 CU 6679",
      "owner_name": "DIPBHAI",
      "owner_mobile": "",
      "bank_details": "Hdfc"
    },
    {
      "id": "10",
      "truck_no": "GJ 03 CU 7000",
      "owner_name": "HARPAL ENTERPRISE",
      "owner_mobile": "",
      "bank_details": ""
    },
    {
      "id": "7",
      "truck_no": "GJ 03 CU 9064",
      "owner_name": "AAL LALABHAI",
      "owner_mobile": "",
      "bank_details": "kotak"
    },
    {
      "id": "12",
      "truck_no": "GJ 03 CU 9886",
      "owner_name": "KANZARIYA",
      "owner_mobile": "",
      "bank_details": "icici"
    },
    {
      "id": "25",
      "truck_no": "GJ 03 CW 1006",
      "owner_name": "VIJAYBHAI BAMBHVA",
      "owner_mobile": "",
      "bank_details": "UJJIVAN SMALL FINANCE BANK"
    },
    {
      "id": "22",
      "truck_no": "GJ 12 BZ 2108",
      "owner_name": "ROHITBHAI SAPARA",
      "owner_mobile": "",
      "bank_details": "HDFC"
    },
    {
      "id": "2",
      "truck_no": "GJ 12 BZ 8848",
      "owner_name": "RANCHHOD SAMJI",
      "owner_mobile": "",
      "bank_details": "HDFC"
    },
    {
      "id": "9",
      "truck_no": "GJ 32 V 1503",
      "owner_name": "JASUBHAI",
      "owner_mobile": "",
      "bank_details": "SBI"
    },
    {
      "id": "23",
      "truck_no": "GJ 37 T 7149",
      "owner_name": "LAKHABHAI GAMARA",
      "owner_mobile": "",
      "bank_details": "SBI"
    },
    {
      "id": "28",
      "truck_no": "GJ 37 V 2626",
      "owner_name": "PAPU SHIVA DHORIYA",
      "owner_mobile": "",
      "bank_details": "HDFC"
    },
    {
      "id": "24",
      "truck_no": "GJ 37 V 5002",
      "owner_name": "MADAM PARBATBHAI",
      "owner_mobile": "",
      "bank_details": "AXIS"
    },
    {
      "id": "27",
      "truck_no": "GJ 37 V 6970",
      "owner_name": "GOJIYA BHARATBHAI",
      "owner_mobile": "",
      "bank_details": "SBI"
    },
    {
      "id": "18",
      "truck_no": "GJ 39 TA 6199",
      "owner_name": "NARANBHAI",
      "owner_mobile": "",
      "bank_details": "AXIS BANK"
    },
    {
      "id": "26",
      "truck_no": "GJ 39 TB 4255",
      "owner_name": "RAHULBHAI BALIYA",
      "owner_mobile": "",
      "bank_details": ""
    },
    {
      "id": "6",
      "truck_no": "GJ 39 TB 9201",
      "owner_name": "ISHWAR PATEL",
      "owner_mobile": "",
      "bank_details": "HDFC"
    },
    {
      "id": "3",
      "truck_no": "GJ 39 TB 9203",
      "owner_name": "ISHWAR PATEL",
      "owner_mobile": "",
      "bank_details": "HDFC BANK"
    },
    {
      "id": "4",
      "truck_no": "GJ 39 TB 9253",
      "owner_name": "ISHWAR PATEL",
      "owner_mobile": "",
      "bank_details": "HDFC"
    },
    {
      "id": "5",
      "truck_no": "GJ 39 TB 9254",
      "owner_name": "ISHWAR PATEL",
      "owner_mobile": "",
      "bank_details": "HDFC"
    }
  ],
  "routes": [
    {
      "id": "13",
      "loading_point": "ANJAR",
      "unloading_point": "SIKKA"
    },
    {
      "id": "7",
      "loading_point": "ANKLESHWAR",
      "unloading_point": "PIPAVAV"
    },
    {
      "id": "5",
      "loading_point": "BHUJ",
      "unloading_point": "WANKANER"
    },
    {
      "id": "2",
      "loading_point": "DAHEJ",
      "unloading_point": "KANDLA"
    },
    {
      "id": "8",
      "loading_point": "DAHEJ",
      "unloading_point": "PIPAVAV"
    },
    {
      "id": "12",
      "loading_point": "DAHEJ",
      "unloading_point": "SANAND"
    },
    {
      "id": "11",
      "loading_point": "DHANETI",
      "unloading_point": "JAMNAGAR"
    },
    {
      "id": "9",
      "loading_point": "DHANETI",
      "unloading_point": "LALPAR"
    },
    {
      "id": "10",
      "loading_point": "ESAAR",
      "unloading_point": "HALOL"
    },
    {
      "id": "6",
      "loading_point": "RELINCE",
      "unloading_point": "JAGHADIA"
    },
    {
      "id": "1",
      "loading_point": "WELPSUN",
      "unloading_point": "SIKKA"
    },
    {
      "id": "3",
      "loading_point": "WELSPUN",
      "unloading_point": "DCC"
    },
    {
      "id": "4",
      "loading_point": "WELSPUN",
      "unloading_point": "SIKKA"
    }
  ],
  "materials": [
    {
      "id": "MAT-1",
      "material_name": "AEMRI"
    },
    {
      "id": "MAT-2",
      "material_name": "COPPER SLAG"
    },
    {
      "id": "MAT-3",
      "material_name": "SALG"
    },
    {
      "id": "MAT-4",
      "material_name": "SILICA"
    },
    {
      "id": "MAT-5",
      "material_name": "SLAG"
    },
    {
      "id": "MAT-6",
      "material_name": "SULPHUR"
    }
  ],
  "trips": [
    {
      "id": "4",
      "trip_date": "2026-08-01",
      "party_name": "YADUNANDAN LOGISTICS",
      "truck_no": "GJ 12 BZ 2108",
      "driver_name": "ROHITBHAI SAPARA",
      "driver_mobile": "",
      "material": "SILICA",
      "loading_point": "DHANETI",
      "unloading_point": "JAMNAGAR",
      "weight": 33.62,
      "rate": 650.0,
      "status": "DELIVERED",
      "notes": "Created automatically from Truck Payment History",
      "pod_file_name": "WhatsApp Image 2026-08-01 at 12.55.55 PM.jpeg"
    },
    {
      "id": "3",
      "trip_date": "2026-08-01",
      "party_name": "YADUNANDAN LOGISTICS",
      "truck_no": "GJ 37 V 5002",
      "driver_name": "MADAM PARBATBHAI",
      "driver_mobile": "",
      "material": "SILICA",
      "loading_point": "DHANETI",
      "unloading_point": "JAMNAGAR",
      "weight": 33.65,
      "rate": 650.0,
      "status": "DELIVERED",
      "notes": "TRIP-3",
      "pod_file_name": "WhatsApp Image 2026-08-01 at 12.53.50 PM.jpeg"
    },
    {
      "id": "2",
      "trip_date": "2026-08-01",
      "party_name": "MANOJ & CO.",
      "truck_no": "GJ 37 V 6970",
      "driver_name": "GOJIYA BHARATBHAI",
      "driver_mobile": "",
      "material": "SLAG",
      "loading_point": "ANJAR",
      "unloading_point": "SIKKA",
      "weight": 32.96,
      "rate": 800.0,
      "status": "DELIVERED",
      "notes": "361",
      "pod_file_name": "WhatsApp Image 2026-08-03 at 7.01.23 PM (1).jpeg"
    },
    {
      "id": "1",
      "trip_date": "2026-08-01",
      "party_name": "MANOJ & CO.",
      "truck_no": "GJ 37 V 2626",
      "driver_name": "PAPU SHIVA DHORIYA",
      "driver_mobile": "",
      "material": "SLAG",
      "loading_point": "ANJAR",
      "unloading_point": "SIKKA",
      "weight": 36.8,
      "rate": 800.0,
      "status": "DELIVERED",
      "notes": "360",
      "pod_file_name": "WhatsApp Image 2026-08-03 at 7.01.23 PM.jpeg"
    }
  ],
  "invoices": [
    {
      "id": "19",
      "invoice_no": "ML - 124",
      "invoice_date": "2026-08-03",
      "party_name": "MANOJ & CO.",
      "party_address": "D.C.C. COLONY , D.C.C. MARKET SIKKA, JAMNAGAR, GUJARAT, 361140",
      "party_gst": "24AACH1790E1Z5",
      "lr_no": "360",
      "material": "SLAG",
      "loading_date": "2026-08-01",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 29440.0,
      "gst_amount": 5299.2,
      "total": 34739.2,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "18",
      "invoice_no": "ML - 123",
      "invoice_date": "2026-08-03",
      "party_name": "MANOJ & CO.",
      "party_address": "D.C.C. COLONY , D.C.C. MARKET SIKKA, JAMNAGAR, GUJARAT, 361140",
      "party_gst": "24AACH1790E1Z5",
      "lr_no": "361",
      "material": "SLAG",
      "loading_date": "2026-08-01",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 26368.0,
      "gst_amount": 4746.24,
      "total": 31114.24,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "17",
      "invoice_no": "ML - 122",
      "invoice_date": "2026-08-01",
      "party_name": "SAANAVI ENTERPRISE",
      "party_address": "SAIDHAM RESIDANCY AA/22 ANKLESHWAR, 393001, NEAR MULAD CHOWKDI, GUJARAT-393001",
      "party_gst": "24BESPD3841P1Z1",
      "lr_no": "SE",
      "material": "COPPER SLAG",
      "loading_date": "2026-07-28",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 36900.0,
      "gst_amount": 6642.0,
      "total": 43542.0,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "16",
      "invoice_no": "ML - 121",
      "invoice_date": "2026-07-31",
      "party_name": "SAANAVI ENTERPRISE",
      "party_address": "SAIDHAM RESIDANCY AA/22 ANKLESHWAR, 393001, NEAR MULAD CHOWKDI, GUJARAT-393001",
      "party_gst": "24BESPD3841P1Z1",
      "lr_no": "SE",
      "material": "COPPER SLAG",
      "loading_date": "2026-07-28",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 25680.0,
      "gst_amount": 4622.4,
      "total": 30302.4,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "15",
      "invoice_no": "ML - 120",
      "invoice_date": "2026-08-01",
      "party_name": "YADUNANDAN LOGISTICS",
      "party_address": "SHOP NO-3, HARI OM AVENUE, NR SHAINIK BHAVAN,KAHMBHALIYA ROA , JAMNAGAR, GUJARAT - 361005",
      "party_gst": "24AXPPT9220P1ZL",
      "lr_no": "TRIP-3",
      "material": "SILICA",
      "loading_date": "2026-08-01",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 21872.5,
      "gst_amount": 3937.05,
      "total": 25809.55,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "13",
      "invoice_no": "ML - 118",
      "invoice_date": "2026-07-25",
      "party_name": "SHREE SATGURU TRANSPORT",
      "party_address": "plot no 23, sadguru smart village, moti bhujpur, taluka mundra, dist : kachchh, pincode - 370405\n",
      "party_gst": "24EQAPS4036L1ZN",
      "lr_no": "328",
      "material": "SLAG",
      "loading_date": "2026-07-10",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 33208.0,
      "gst_amount": 5977.44,
      "total": 39185.44,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "12",
      "invoice_no": "ML - 117",
      "invoice_date": "2026-07-25",
      "party_name": "SHREE SATGURU TRANSPORT",
      "party_address": "plot no 23, sadguru smart village, moti bhujpur, taluka mundra, dist : kachchh, pincode - 370405\n",
      "party_gst": "24EQAPS4036L1ZN",
      "lr_no": "332",
      "material": "SLAG",
      "loading_date": "2026-07-10",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 34312.0,
      "gst_amount": 6176.16,
      "total": 40488.16,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "11",
      "invoice_no": "ML - 116",
      "invoice_date": "2026-07-25",
      "party_name": "SHREE DWARKADHISH ENTERPRISE",
      "party_address": "SECOND FLOOR, NEAR J M BAXI, THE PRIME, SHOP NO. SF/201, BEDI, JAMNAGAR 361009\n",
      "party_gst": "24AACPH1792G1ZZ",
      "lr_no": "144",
      "material": "SULPHUR",
      "loading_date": "2026-07-08",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 53396.0,
      "gst_amount": 9611.28,
      "total": 63007.28,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "10",
      "invoice_no": "ML - 115",
      "invoice_date": "2026-07-23",
      "party_name": "DIGVIJAY MINERALS",
      "party_address": "SURVEY NO 93/P1 AND 93/P2 LAKHOND KALI TALAVDI ROAD, KALI TALAVDI, BHUJ,KUTCHCHH,GUJARAT, 370001",
      "party_gst": "24AASFD1386N1ZV",
      "lr_no": "DM",
      "material": "AEMRI",
      "loading_date": "2026-07-21",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 27060.0,
      "gst_amount": 4870.8,
      "total": 31930.8,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "9",
      "invoice_no": "ML - 114",
      "invoice_date": "2026-07-23",
      "party_name": "DIGVIJAY MINERALS",
      "party_address": "SURVEY NO 93/P1 AND 93/P2 LAKHOND KALI TALAVDI ROAD, KALI TALAVDI, BHUJ,KUTCHCHH,GUJARAT, 370001",
      "party_gst": "24AASFD1386N1ZV",
      "lr_no": "DM",
      "material": "AEMRI",
      "loading_date": "2026-07-20",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 27830.0,
      "gst_amount": 5009.4,
      "total": 32839.4,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "8",
      "invoice_no": "ML - 113",
      "invoice_date": "2026-07-18",
      "party_name": "SHREE DWARKADHISH ENTERPRISE",
      "party_address": "SECOND FLOOR, NEAR J M BAXI, THE PRIME, SHOP NO. SF/201, BEDI, JAMNAGAR 361009\n",
      "party_gst": "24AACPH1792G1ZZ",
      "lr_no": "147",
      "material": "SULPHUR",
      "loading_date": "2026-07-10",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 55398.0,
      "gst_amount": 9971.64,
      "total": 65369.64,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "7",
      "invoice_no": "ML - 112",
      "invoice_date": "2026-07-18",
      "party_name": "SHREE DWARKADHISH ENTERPRISE",
      "party_address": "SECOND FLOOR, NEAR J M BAXI, THE PRIME, SHOP NO. SF/201, BEDI, JAMNAGAR 361009\n",
      "party_gst": "24AACPH1792G1ZZ",
      "lr_no": "146",
      "material": "SULPHUR",
      "loading_date": "2026-07-09",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 53452.0,
      "gst_amount": 9621.36,
      "total": 63073.36,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "6",
      "invoice_no": "ML - 111",
      "invoice_date": "2026-07-18",
      "party_name": "SHREE DWARKADHISH ENTERPRISE",
      "party_address": "SECOND FLOOR, NEAR J M BAXI, THE PRIME, SHOP NO. SF/201, BEDI, JAMNAGAR 361009\n",
      "party_gst": "24AACPH1792G1ZZ",
      "lr_no": "145",
      "material": "SULPHUR",
      "loading_date": "2026-07-09",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 53900.0,
      "gst_amount": 9702.0,
      "total": 63602.0,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "5",
      "invoice_no": "ML - 110",
      "invoice_date": "2026-07-18",
      "party_name": "MANOJ & CO.",
      "party_address": "D.C.C. COLONY , D.C.C. MARKET SIKKA, JAMNAGAR, GUJARAT, 361140",
      "party_gst": "24AACH1790E1Z5",
      "lr_no": "280",
      "material": "SALG",
      "loading_date": "2026-07-03",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 29088.0,
      "gst_amount": 5235.84,
      "total": 34323.84,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "4",
      "invoice_no": "ML - 109",
      "invoice_date": "2026-07-25",
      "party_name": "SAANAVI ENTERPRISE",
      "party_address": "SAIDHAM RESIDANCY AA/22 ANKLESHWAR, 393001, NEAR MULAD CHOWKDI, GUJARAT-393001",
      "party_gst": "24BESPD3841P1Z1",
      "lr_no": "SE",
      "material": "COPPER SLAG",
      "loading_date": "2026-07-23",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 32256.0,
      "gst_amount": 5806.08,
      "total": 38062.08,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "3",
      "invoice_no": "ML - 108",
      "invoice_date": "2026-07-18",
      "party_name": "SAANAVI ENTERPRISE",
      "party_address": "SAIDHAM RESIDANCY AA/22 ANKLESHWAR, 393001, NEAR MULAD CHOWKDI, GUJARAT-393001",
      "party_gst": "24BESPD3841P1Z1",
      "lr_no": "SE",
      "material": "COPPER SLAG",
      "loading_date": "2026-07-16",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 31500.0,
      "gst_amount": 5670.0,
      "total": 37170.0,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "2",
      "invoice_no": "ML - 107",
      "invoice_date": "2026-07-18",
      "party_name": "SAANAVI ENTERPRISE",
      "party_address": "SAIDHAM RESIDANCY AA/22 ANKLESHWAR, 393001, NEAR MULAD CHOWKDI, GUJARAT-393001",
      "party_gst": "24BESPD3841P1Z1",
      "lr_no": "SE",
      "material": "COPPER SLAG",
      "loading_date": "2026-07-13",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 31950.0,
      "gst_amount": 5751.0,
      "total": 37701.0,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    },
    {
      "id": "1",
      "invoice_no": "ML - 106",
      "invoice_date": "2026-07-18",
      "party_name": "SAANAVI ENTERPRISE",
      "party_address": "SAIDHAM RESIDANCY AA/22 ANKLESHWAR, 393001, NEAR MULAD CHOWKDI, GUJARAT-393001",
      "party_gst": "24BESPD3841P1Z1",
      "lr_no": "SE",
      "material": "COPPER SLAG",
      "loading_date": "2026-07-08",
      "sgst": 9.0,
      "cgst": 9.0,
      "diesel": 0.0,
      "munshi": 0.0,
      "subtotal": 41085.0,
      "gst_amount": 7395.3,
      "total": 48480.3,
      "comments": "1. In 30 days, you must pay the total.\n2. In the check, please include your invoice number."
    }
  ],
  "invoice_items": [
    {
      "id": "1959d955-f7d4-453f-b3c5-4c6cd88e5800",
      "invoice_id": "19",
      "trip_id": "1",
      "truck_no": "GJ 37 V 2626",
      "description": "ANJAR TO SIKKA",
      "weight": 36.8,
      "rate": 800.0,
      "amount": 29440.0,
      "loading_weight": 36.8,
      "unloading_weight": 36.8,
      "shortage": 0
    },
    {
      "id": "18517636-0428-436f-bf1d-1823206ebbaf",
      "invoice_id": "18",
      "trip_id": "2",
      "truck_no": "GJ 37 V 6970",
      "description": "ANJAR TO SIKKA",
      "weight": 32.96,
      "rate": 800.0,
      "amount": 26368.0,
      "loading_weight": 32.96,
      "unloading_weight": 32.96,
      "shortage": 0
    },
    {
      "id": "e6b8234c-f487-49d4-b243-25678ece9b65",
      "invoice_id": "17",
      "trip_id": "",
      "truck_no": "GJ 39 TB 4255",
      "description": "DAHEJ TO PIPAVAV",
      "weight": 41.0,
      "rate": 900.0,
      "amount": 36900.0,
      "loading_weight": 41.0,
      "unloading_weight": 41.0,
      "shortage": 0
    },
    {
      "id": "trip-1",
      "invoice_id": "16",
      "trip_id": "",
      "truck_no": "GJ 03 CW 1006",
      "description": "DAHEJ TO SANAND",
      "weight": 42.8,
      "rate": 600.0,
      "amount": 25680.0,
      "loading_weight": 42.8,
      "unloading_weight": 42.8,
      "shortage": 0
    },
    {
      "id": "502b420c-b1d8-4d28-a3e0-302d949eff7d",
      "invoice_id": "15",
      "trip_id": "3",
      "truck_no": "GJ 37 V 5002",
      "description": "DHANETI TO JAMNAGAR",
      "weight": 33.65,
      "rate": 650.0,
      "amount": 21872.5,
      "loading_weight": 33.65,
      "unloading_weight": 33.65,
      "shortage": 0
    },
    {
      "id": "59ff9aec-67ed-461f-8c15-e1904c7dc000",
      "invoice_id": "13",
      "trip_id": "",
      "truck_no": "GJ 39 TB 9252",
      "description": "WELSPUN TO DCC",
      "weight": 41.51,
      "rate": 800.0,
      "amount": 33208.0,
      "loading_weight": 41.51,
      "unloading_weight": 41.51,
      "shortage": 0
    },
    {
      "id": "trip-1",
      "invoice_id": "12",
      "trip_id": "",
      "truck_no": "GJ 39 TB 9251",
      "description": "WELSPUN TO DCC",
      "weight": 42.89,
      "rate": 800.0,
      "amount": 34312.0,
      "loading_weight": 42.89,
      "unloading_weight": 42.89,
      "shortage": 0
    },
    {
      "id": "trip-1",
      "invoice_id": "11",
      "trip_id": "",
      "truck_no": "GJ 03 CU 6679",
      "description": "RELINCE TO JHAGADIA",
      "weight": 38.14,
      "rate": 1400.0,
      "amount": 53396.0,
      "loading_weight": 38.14,
      "unloading_weight": 38.14,
      "shortage": 0
    },
    {
      "id": "adf79485-a340-43f0-a652-84cfd7ea87b6",
      "invoice_id": "10",
      "trip_id": "",
      "truck_no": "GJ 03 CU 9886",
      "description": "DHANETI TO LALPAR",
      "weight": 49.2,
      "rate": 550.0,
      "amount": 27060.0,
      "loading_weight": 49.2,
      "unloading_weight": 49.2,
      "shortage": 0
    },
    {
      "id": "73d7fbdc-7306-4048-a9f7-2fd2381ec234",
      "invoice_id": "9",
      "trip_id": "",
      "truck_no": "GJ 39 TA 6199",
      "description": "DHANETI TO LALPAR",
      "weight": 50.6,
      "rate": 550.0,
      "amount": 27830.0,
      "loading_weight": 50.6,
      "unloading_weight": 50.6,
      "shortage": 0
    },
    {
      "id": "1d99b612-8e2f-419a-a4cc-650acdfabe4b",
      "invoice_id": "8",
      "trip_id": "",
      "truck_no": "GJ 03 CU 7919",
      "description": "RELINCE TO JHAGADIA",
      "weight": 39.57,
      "rate": 1400.0,
      "amount": 55398.0,
      "loading_weight": 39.57,
      "unloading_weight": 39.57,
      "shortage": 0
    },
    {
      "id": "d4922580-32f1-482e-ad65-5672a464a7fd",
      "invoice_id": "7",
      "trip_id": "",
      "truck_no": "GJ 03 CU 9064",
      "description": "RELINCE TO JHAGADIA",
      "weight": 38.18,
      "rate": 1400.0,
      "amount": 53452.0,
      "loading_weight": 38.18,
      "unloading_weight": 38.18,
      "shortage": 0
    },
    {
      "id": "48a1eb26-0729-4cd5-976e-0f44328664ac",
      "invoice_id": "6",
      "trip_id": "",
      "truck_no": "GJ 03 CU 5608",
      "description": "RELINCE TO JHAGADIA",
      "weight": 38.5,
      "rate": 1400.0,
      "amount": 53900.0,
      "loading_weight": 38.5,
      "unloading_weight": 38.5,
      "shortage": 0
    },
    {
      "id": "trip-1",
      "invoice_id": "5",
      "trip_id": "",
      "truck_no": "GJ 37 V 8587",
      "description": "WELSPU ANJAR TO DCC SIKKA",
      "weight": 36.36,
      "rate": 800.0,
      "amount": 29088.0,
      "loading_weight": 36.36,
      "unloading_weight": 36.36,
      "shortage": 0
    },
    {
      "id": "c588c70c-1119-46e3-9dee-282f542c3f2a",
      "invoice_id": "4",
      "trip_id": "",
      "truck_no": "GJ 03 BT 5925",
      "description": "DAHEJ TO KANDLA",
      "weight": 35.84,
      "rate": 900.0,
      "amount": 32256.0,
      "loading_weight": 35.84,
      "unloading_weight": 35.84,
      "shortage": 0
    },
    {
      "id": "c20040b9-821a-4692-bfc6-2f5e3a478886",
      "invoice_id": "3",
      "trip_id": "",
      "truck_no": "GJ 03 BW 4387",
      "description": "DAHEJ TO PIPAVAV",
      "weight": 35.0,
      "rate": 900.0,
      "amount": 31500.0,
      "loading_weight": 35.0,
      "unloading_weight": 35.0,
      "shortage": 0
    },
    {
      "id": "77ca4ab3-8d55-44a5-9ab7-399b68924082",
      "invoice_id": "2",
      "trip_id": "",
      "truck_no": "GJ 32 V 1503",
      "description": "DAHEJ TO PIPAVAV",
      "weight": 35.5,
      "rate": 900.0,
      "amount": 31950.0,
      "loading_weight": 35.5,
      "unloading_weight": 35.5,
      "shortage": 0
    },
    {
      "id": "2eb99f4d-e27c-4b34-9bbe-1131922dc712",
      "invoice_id": "1",
      "trip_id": "",
      "truck_no": "GJ 03 CU 3351",
      "description": "DAHEJ TO KANDLA",
      "weight": 45.65,
      "rate": 900.0,
      "amount": 41085.0,
      "loading_weight": 45.65,
      "unloading_weight": 45.65,
      "shortage": 0
    }
  ],
  "truck_entries": [
    {
      "id": "26",
      "trip_id": "1",
      "entry_date": "2026-08-01",
      "truck_no": "GJ 37 V 2626",
      "owner_name": "PAPU SHIVA DHORIYA",
      "bank_details": "HDFC",
      "loading_point": "ANJAR",
      "unloading_point": "SIKKA",
      "weight": 36.8,
      "rate": 750.0,
      "commission": 800.0,
      "payable": 26800.0,
      "notes": "TRIP-ID:1 · 360"
    },
    {
      "id": "25",
      "trip_id": "2",
      "entry_date": "2026-08-01",
      "truck_no": "GJ 37 V 6970",
      "owner_name": "GOJIYA BHARATBHAI",
      "bank_details": "SBI",
      "loading_point": "ANJAR",
      "unloading_point": "SIKKA",
      "weight": 32.96,
      "rate": 750.0,
      "commission": 800.0,
      "payable": 23920.0,
      "notes": "TRIP-ID:2 · 361"
    },
    {
      "id": "24",
      "trip_id": "",
      "entry_date": "2026-08-01",
      "truck_no": "GJ 03 CW 1006",
      "owner_name": "VIJAYBHAI BAMBHVA",
      "bank_details": "UJJIVAN SMALL FINANCE BANK",
      "loading_point": "DAHEJ",
      "unloading_point": "SANAND",
      "weight": 42.8,
      "rate": 550.0,
      "commission": 800.0,
      "payable": 22740.0,
      "notes": ""
    },
    {
      "id": "23",
      "trip_id": "3",
      "entry_date": "2026-08-01",
      "truck_no": "GJ 37 V 5002",
      "owner_name": "MADAM PARBATBHAI",
      "bank_details": "AXIS",
      "loading_point": "DHANETI",
      "unloading_point": "JAMNAGAR",
      "weight": 33.65,
      "rate": 650.0,
      "commission": 500.0,
      "payable": 21372.5,
      "notes": "TRIP-ID:3 · TRIP-3"
    },
    {
      "id": "22",
      "trip_id": "",
      "entry_date": "2026-08-01",
      "truck_no": "GJ 37 T 7149",
      "owner_name": "LAKHABHAI GAMARA",
      "bank_details": "SBI",
      "loading_point": "DHANETI",
      "unloading_point": "JAMNAGAR",
      "weight": 33.21,
      "rate": 650.0,
      "commission": 500.0,
      "payable": 21086.5,
      "notes": ""
    },
    {
      "id": "20",
      "trip_id": "4",
      "entry_date": "2026-08-01",
      "truck_no": "GJ 12 BZ 2108",
      "owner_name": "ROHITBHAI SAPARA",
      "bank_details": "HDFC",
      "loading_point": "DHANETI",
      "unloading_point": "JAMNAGAR",
      "weight": 33.62,
      "rate": 650.0,
      "commission": 500.0,
      "payable": 21353.0,
      "notes": "TRIP-ID:4 · Created automatically from Truck Payment History"
    },
    {
      "id": "19",
      "trip_id": "",
      "entry_date": "2026-07-28",
      "truck_no": "GJ 03 CU 6679",
      "owner_name": "DIPBHAI",
      "bank_details": "Hdfc",
      "loading_point": "RELINCE",
      "unloading_point": "JAGHADIA",
      "weight": 38.1,
      "rate": 1300.0,
      "commission": 800.0,
      "payable": 48730.0,
      "notes": ""
    },
    {
      "id": "18",
      "trip_id": "",
      "entry_date": "2026-07-27",
      "truck_no": "GJ 03 CU 3818",
      "owner_name": "KANZARIYA",
      "bank_details": "",
      "loading_point": "RELINCE",
      "unloading_point": "JAGHADIA",
      "weight": 38.47,
      "rate": 1380.0,
      "commission": 800.0,
      "payable": 52288.6,
      "notes": ""
    },
    {
      "id": "17",
      "trip_id": "",
      "entry_date": "2026-07-27",
      "truck_no": "GJ 03 CU 3818",
      "owner_name": "KANZARIYA",
      "bank_details": "",
      "loading_point": "RELINCE",
      "unloading_point": "JAGHADIA",
      "weight": 35.69,
      "rate": 1350.0,
      "commission": 800.0,
      "payable": 47381.5,
      "notes": ""
    },
    {
      "id": "16",
      "trip_id": "",
      "entry_date": "2026-07-25",
      "truck_no": "GJ 03 CU 6679",
      "owner_name": "DIPBHAI",
      "bank_details": "Hdfc",
      "loading_point": "ESAAR",
      "unloading_point": "HALOL",
      "weight": 26.965,
      "rate": 1500.0,
      "commission": 800.0,
      "payable": 39647.5,
      "notes": ""
    },
    {
      "id": "15",
      "trip_id": "",
      "entry_date": "2026-07-25",
      "truck_no": "GJ 39 TA 6199",
      "owner_name": "NARANBHAI",
      "bank_details": "AXIS BANK",
      "loading_point": "DHANETI",
      "unloading_point": "LALPAR",
      "weight": 50.9,
      "rate": 500.0,
      "commission": 500.0,
      "payable": 24950.0,
      "notes": ""
    },
    {
      "id": "14",
      "trip_id": "",
      "entry_date": "2026-07-25",
      "truck_no": "GJ 03 BT 5925",
      "owner_name": "BHIMSHIBHAI",
      "bank_details": "IDBI",
      "loading_point": "DAHEJ",
      "unloading_point": "KANDLA",
      "weight": 35.84,
      "rate": 900.0,
      "commission": 800.0,
      "payable": 31456.0,
      "notes": ""
    },
    {
      "id": "13",
      "trip_id": "",
      "entry_date": "2026-07-25",
      "truck_no": "GJ 03 CU 9886",
      "owner_name": "KANZARIYA",
      "bank_details": "icici",
      "loading_point": "DHANETI",
      "unloading_point": "LALPAR",
      "weight": 49.44,
      "rate": 500.0,
      "commission": 800.0,
      "payable": 23920.0,
      "notes": ""
    },
    {
      "id": "12",
      "trip_id": "",
      "entry_date": "2026-07-22",
      "truck_no": "GJ 03 BW 4387",
      "owner_name": "MUKESHBHAI",
      "bank_details": "hdfc",
      "loading_point": "DAHEJ",
      "unloading_point": "PIPAVAV",
      "weight": 35.0,
      "rate": 900.0,
      "commission": 800.0,
      "payable": 30700.0,
      "notes": ""
    },
    {
      "id": "11",
      "trip_id": "",
      "entry_date": "2026-07-20",
      "truck_no": "GJ 32 V 1503",
      "owner_name": "JASUBHAI",
      "bank_details": "SBI",
      "loading_point": "ANKLESHWAR",
      "unloading_point": "PIPAVAV",
      "weight": 35.5,
      "rate": 900.0,
      "commission": 800.0,
      "payable": 31150.0,
      "notes": ""
    },
    {
      "id": "10",
      "trip_id": "",
      "entry_date": "2026-07-20",
      "truck_no": "GJ 03 CU 5608",
      "owner_name": "AAL LALABHAI",
      "bank_details": "kotak",
      "loading_point": "RELINCE",
      "unloading_point": "JAGHADIA",
      "weight": 38.5,
      "rate": 1300.0,
      "commission": 800.0,
      "payable": 49250.0,
      "notes": ""
    },
    {
      "id": "9",
      "trip_id": "",
      "entry_date": "2026-07-20",
      "truck_no": "GJ 03 CU 9064",
      "owner_name": "AAL LALABHAI",
      "bank_details": "kotak",
      "loading_point": "RELINCE",
      "unloading_point": "JAGHADIA",
      "weight": 38.18,
      "rate": 1300.0,
      "commission": 800.0,
      "payable": 48834.0,
      "notes": ""
    },
    {
      "id": "8",
      "trip_id": "",
      "entry_date": "2026-07-18",
      "truck_no": "GJ 39 TB 9201",
      "owner_name": "ISHWAR PATEL",
      "bank_details": "HDFC",
      "loading_point": "WELSPUN",
      "unloading_point": "SIKKA",
      "weight": 42.0,
      "rate": 750.0,
      "commission": 800.0,
      "payable": 30700.0,
      "notes": ""
    },
    {
      "id": "7",
      "trip_id": "",
      "entry_date": "2026-07-18",
      "truck_no": "GJ 39 TB 9201",
      "owner_name": "ISHWAR PATEL",
      "bank_details": "HDFC",
      "loading_point": "BHUJ",
      "unloading_point": "WANKANER",
      "weight": 55.8,
      "rate": 500.0,
      "commission": 800.0,
      "payable": 27100.0,
      "notes": ""
    },
    {
      "id": "6",
      "trip_id": "",
      "entry_date": "2026-07-18",
      "truck_no": "GJ 39 TB 9254",
      "owner_name": "ISHWAR PATEL",
      "bank_details": "HDFC",
      "loading_point": "WELSPUN",
      "unloading_point": "SIKKA",
      "weight": 41.4,
      "rate": 750.0,
      "commission": 800.0,
      "payable": 30250.0,
      "notes": ""
    },
    {
      "id": "5",
      "trip_id": "",
      "entry_date": "2026-07-18",
      "truck_no": "GJ 39 TB 9253",
      "owner_name": "ISHWAR PATEL",
      "bank_details": "HDFC",
      "loading_point": "WELSPUN",
      "unloading_point": "SIKKA",
      "weight": 42.27,
      "rate": 750.0,
      "commission": 800.0,
      "payable": 30902.5,
      "notes": ""
    },
    {
      "id": "4",
      "trip_id": "",
      "entry_date": "2026-07-18",
      "truck_no": "GJ 39 TB 9203",
      "owner_name": "ISHWAR PATEL",
      "bank_details": "HDFC BANK",
      "loading_point": "WELSPUN",
      "unloading_point": "DCC",
      "weight": 43.43,
      "rate": 750.0,
      "commission": 800.0,
      "payable": 31772.5,
      "notes": ""
    },
    {
      "id": "3",
      "trip_id": "",
      "entry_date": "2026-07-18",
      "truck_no": "GJ 12 BZ 8848",
      "owner_name": "RANCHHOD SAMJI",
      "bank_details": "HDFC",
      "loading_point": "DAHEJ",
      "unloading_point": "KANDLA",
      "weight": 42.0,
      "rate": 900.0,
      "commission": 800.0,
      "payable": 37000.0,
      "notes": ""
    },
    {
      "id": "2",
      "trip_id": "",
      "entry_date": "2026-07-18",
      "truck_no": "GJ 03 CU 3351",
      "owner_name": "BHURABHAI",
      "bank_details": "ICICI BANK",
      "loading_point": "DAHEJ",
      "unloading_point": "KANDLA",
      "weight": 45.0,
      "rate": 900.0,
      "commission": 800.0,
      "payable": 39700.0,
      "notes": ""
    },
    {
      "id": "1",
      "trip_id": "",
      "entry_date": "2026-07-18",
      "truck_no": "GJ 03 CU 3351",
      "owner_name": "BHURABHAI",
      "bank_details": "ICICI BANK",
      "loading_point": "WELPSUN",
      "unloading_point": "SIKKA",
      "weight": 42.45,
      "rate": 750.0,
      "commission": 800.0,
      "payable": 31037.5,
      "notes": ""
    }
  ],
  "supplier_payments": [
    {
      "id": "SP-18",
      "owner_name": "KANZARIYA",
      "truck_no": "GJ 03 CU 3818",
      "payment_date": "2026-07-27",
      "amount": 52288.0,
      "payment_mode": "CASH",
      "reference": "",
      "notes": "Imported payment for truck entry 18"
    },
    {
      "id": "SP-17",
      "owner_name": "KANZARIYA",
      "truck_no": "GJ 03 CU 3818",
      "payment_date": "2026-07-27",
      "amount": 35000.0,
      "payment_mode": "CASH",
      "reference": "",
      "notes": "Imported payment for truck entry 17"
    },
    {
      "id": "SP-10",
      "owner_name": "AAL LALABHAI",
      "truck_no": "GJ 03 CU 5608",
      "payment_date": "2026-07-20",
      "amount": 25000.0,
      "payment_mode": "BANK",
      "reference": "kotak",
      "notes": "Imported payment for truck entry 10"
    },
    {
      "id": "SP-9",
      "owner_name": "AAL LALABHAI",
      "truck_no": "GJ 03 CU 9064",
      "payment_date": "2026-07-20",
      "amount": 25000.0,
      "payment_mode": "BANK",
      "reference": "kotak",
      "notes": "Imported payment for truck entry 9"
    },
    {
      "id": "SP-8",
      "owner_name": "ISHWAR PATEL",
      "truck_no": "GJ 39 TB 9201",
      "payment_date": "2026-07-18",
      "amount": 25000.0,
      "payment_mode": "BANK",
      "reference": "HDFC",
      "notes": "Imported payment for truck entry 8"
    },
    {
      "id": "SP-7",
      "owner_name": "ISHWAR PATEL",
      "truck_no": "GJ 39 TB 9201",
      "payment_date": "2026-07-18",
      "amount": 25000.0,
      "payment_mode": "BANK",
      "reference": "HDFC",
      "notes": "Imported payment for truck entry 7"
    },
    {
      "id": "SP-1",
      "owner_name": "BHURABHAI",
      "truck_no": "GJ 03 CU 3351",
      "payment_date": "2026-07-18",
      "amount": 20000.0,
      "payment_mode": "BANK",
      "reference": "ICICI BANK",
      "notes": "Imported payment for truck entry 1"
    }
  ],
  "expenses": []
};
